services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        environment:
        - discovery.type=single-node
        - ELASTIC_PASSWORD=pass
        ports:
        - 9200:9200
        networks:
        - net

#    kibana:
#        image: docker.elastic.co/kibana/kibana:7.10.2
#        ports:
#        - 5601:5601
#        networks:
#        - net