services:
#  setup:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
#    volumes:
#      - certs:/usr/share/elasticsearch/config/certs
#    user: "0"
#    command: >
#      bash -c '
#        # Various setup commands...
#      '
#    healthcheck:
#      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
#      interval: 1s
#      timeout: 5s
#      retries: 120
  elasticsearch:
#    depends_on:
#      setup:
#        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    volumes:
      - ./elastic-certs:/usr/share/elasticsearch/config/certs
      - ./elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
#      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=adminadmin
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic



  #    mem_limit: 6442450944
  kibana:
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.15.0
    volumes:
      - ./elastic-kibana-certs:/usr/share/kibana/config/certs
      - ./elastic-kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=adminadmin
      - xpack.security.audit.enabled=false
#      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
#    mem_limit: 6442450944

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local